apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-app-deployment
  labels:
    app: food-app
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: food-app
  template:
    metadata:
      labels:
        app: food-app
    spec:
      containers:
      - name: food-app-ctn
        image: food-app:1
        imagePullPolicy: Never
        env:
        - name: MOCKSERVER_INITIALIZATION_JSON_PATH
          value: "/config/mockserverInitialization.json"
        ports:
        - containerPort: 1080